### PR TITLE
modify console cmd for new minio version requirement

### LINKED ISSUE #16: Latest MinIO version broke this plugin
Recently I set up another dokku environment running MinIO, using this plugin.

Since MinIo released a new version - see https://github.com/minio/minio/releases/tag/RELEASE.2021-07-08T01-15-01Z - which replaces the "old" webUI with the MinIO console project, this repository / dokku prepared image does not work anymore.

> Embedded MinIO Browser removed replaced with MinIO Console project https://github.com/minio/console, this is a breaking change

As a workaround I'm using an older version of MinIO until such fix is provided in the repo.

### PR DESCRIPTION
**Pull request by AyodejiO**
Fixes #16

### CODE REVIEW

**Comment by AyodejiO** [comment]
Note: If the port in the Dockerfile changes, then the reverse proxy must also do the same. Refer to initial documentation for more understanding.

**Comment by AyodejiO** [comment]
https://github.com/minio/minio/issues/12660

**Comment by turicas** [comment]
@AyodejiO I've created #21, which is going to expose both ports (API and console) through HTTPS.

**Comment by sheepyhollow** [comment]
should be made obsolete by #21

**Pull request closed without merging**
